Epic invoker compiler
gurovic/Strategy_game pull request #114
Opened 2023-11-17 10:24 UTC by derwesx

CodeReview Only.

2023-11-17 11:18 UTC, MrNereof reviewed
С пивом покатит🍺

2023-11-17 12:00 UTC, gurovic requested changes

2023-11-17 12:00 UTC, gurovic commented on website/website/__pycache__/__init__.cpython-310.pyc
нужно убрать эти файлы из репозитория

2023-11-17 12:00 UTC, gurovic commented on website/app/models/compiler.py
у нас два компайлера?

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_pool.py
> +        for invoker in self.all_invokers:
а почему нельзя отдельно хранить множество свободных и множество занятых инвокеров? 
зачем каждый раз перебирать все?

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker.py
> +class Invoker:
не соответствует документации

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker.py
> +    def run(self, command: str, files: typing.Optional[list[str | File]] = None,
не пишутся логи сайта о работе инвокера

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker.py
> +        result = subprocess.run(command.split() if isinstance(command, str) else command, text=True,
timeout?

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_multi_request.py
> +        from invoker.invoker_multi_request_priority_queue import InvokerMultiRequestPriorityQueue
import вынести в начало файла

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_multi_request.py
> +    def start(self):
странно, что это в этом классе, хотя понятно, из-за чего

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_multi_request.py
> +        self.subscribers = []
а где метод subscribe? кто добавляет в этот список?

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_multi_request_priority_queue.py
>      def notify(self):
?

2023-11-17 12:00 UTC, gurovic commented on website/invoker/invoker_pool.py
> +class InvokerPool:
а почему не синглетон, я так и не понял

2023-11-17 12:11 UTC, derwesx commented on website/invoker/invoker_pool.py
> +class InvokerPool:
InvokerPool привязан к определенной IMRPQueue, которая есть в проекте. Таких очередей у нас будет несколько, они разные классы и разные по функционалу, но при этом каждой из них нужен InvokerPool со своим кол-вом Invokers, который общий везде по функционалу.

2023-11-17 12:28 UTC, derwesx commented on website/invoker/invoker_request.py
> +        self.report = report
Нет.

2023-11-17 13:58 UTC, derwesx commented on website/invoker/invoker_multi_request.py
> +    def start(self):
Пока что костыль.

2023-11-17 19:30 UTC, MrNereof commented on website/app/models/compiler.py
Пока да, потом добавим ещё

2023-11-17 19:45 UTC, derwesx commented on website/invoker/invoker.py
> +    def run(self, command: str, files: typing.Optional[list[str | File]] = None,
Проблем нет.

2023-11-17 19:47 UTC, derwesx commented on website/invoker/invoker_pool.py
> +        for invoker in self.all_invokers:
Удалять из одного списка, добавлять в другой (освободившиеся инвокеры) (у них может быть случайное расположение в списке занятых) по асимптотике ~= полному перебору. Хранить только свободные не очень, т.к. можно легко потерять.

2023-11-17 19:57 UTC, MrNereof commented on website/invoker/models.py
> +class InvokerReport(models.Model):
Добавил input_files

2023-11-18 11:36 UTC, gurovic commented on website/invoker/invoker_pool.py
> +class InvokerPool:
А зачем нужно несколько очередей? Иметь несколько инвокерпулов кажется бессмысленным, потому что у нас есть железное ограничение на количество инвокеров во всех пулах в сумме.

2023-11-18 11:36 UTC, gurovic commented on website/invoker/invoker_pool.py
> +        for invoker in self.all_invokers:
Множества?

2023-11-18 11:36 UTC, gurovic commented on website/app/compiler.py
> +    OUTPUT_FILE_NAME = "compiled"
неясно, куда складываются exe-шники, и с какими именами

2023-11-19 13:52 UTC, derwesx commented on website/app/compiler.py
> +    OUTPUT_FILE_NAME = "compiled"
Выкачивается обратно инвокером после компиляции (рассмотрим в спринте как взаимодействовать с батлом будет)

2023-11-19 14:11 UTC, MrNereof commented on website/app/compiler.py
> +    OUTPUT_FILE_NAME = "compiled"
Это названия файлов внутри окружения Invoker. После выполнения они сохраняются в InvokerReport, откуда потом могут быть легко получены. За название и расположение отвечает Django.

2023-11-19 16:37 UTC, gurovic commented on requirements.txt
> +Django~=4.2.5
1. Мы договорились не менять версию джанго в процессе разработки
2. Мы прописали версию джанго в вики
3. Мы договорились не включать изменения, не имеющие отношения к данной задаче, в коммит

2023-11-19 16:37 UTC, gurovic commented on website/invoker/invoker_pool.py
> +import logging, multiset
зачем?

2023-11-19 17:00 UTC, gurovic approved these changes

2023-11-19 17:01 UTC, merged