Invoker structure
gurovic/Strategy_game pull request #31
Opened 2023-10-17 12:21 UTC by derwesx

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerPool.py
> +        if self.all_invokers[invokerid].status == InvokerStatus.WORKING:
invokerid - это не индекс в списке

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerPool.py
> +            return None
типа пусть ошибка вылетает не здесь, а где-то в коде выше?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerPool.py
> +        for invoker in self.all_invokers:
проще хранить список свободных и список занятых инвокеров, чем каждый раз искать свободный в списке всех

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerPool.py
> +        for invoker in self.all_invokers:
нехорошо использовать for с break вместо while

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +logging.basicConfig(filename='LOG.log', level=logging.DEBUG,
это нужно вынести (в таком виде оно выполняется при каждом импорте)

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +    invokerMultiRequestQueue = PriorityQueue()
перенести в init

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +    invokerMultiRequestQueue = PriorityQueue()
названия переменных - через подчеркивание маленькими буквами

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +    def run(self):
когда и кем запускается run?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +        while freeinvokerscount < invokermultirequest.invoker_requests_count:
так не надо - подписка!

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequestsPriorityQueue.py
> +    def add(self, invokermultirequest: [InvokerMultiRequest], priority):
что означают квадратные скобки?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequests.py
> +    def __init__(self, invoker_requests: [InvokerRequest], creator, priority):
list[InvokerRequest]?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequests.py
> +    def run(self, ids: [int]):
list[int]?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequests.py
> +            self.invoker_requests[i].run(ids[i])
а как стратегии будут взаимодействовать между собой?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/SETTINGS.py
> +# Created at 2023/10/17
в именах файлов НЕЛЬЗЯ использовать заглавные буквы - для винды это тот же файл, что и маленькими буквами, а для Linux - другой. Гиту становится плохо...

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invokerMultiRequests.py
> +        self.creator = creator
а где он используется?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invoker.py
> +            subscriber.notify(self.id, report)
после этого нужно удалять его из подписчиков?

2023-10-17 12:51 UTC, gurovic commented on invokersstructure/invoker.py
> +        for subscriber in self.subscribers:
это должно быть не здесь - subprocess не закончил свою работу

2023-10-22 13:07 UTC, MrNereof requested changes

2023-10-22 13:07 UTC, MrNereof commented on invokersstructure/SETTINGS.py
> +ALL_INVOKERS_COUNT = 100
Мне не нравится, создание файла настроек вне джанговского settings.py. Все подобные настраиваемые переменные можно помещать в него и получать через django.conf.settings.

2023-10-26 11:19 UTC, closed without merging